name: first workflow
on: disspatch_workflow
jobs:
  first job:
    runs-on: ubuntu-latest
      steps:
        - name: print greeting
		  run: echo "hello world"
		- name: print goodbye
		  run: echo "hello bye"
